# fly.toml file generated for app-dating on 2023-01-26T15:01:56-05:00

app = "app-dating"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "saikodari/datingapp"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="da5oqul8a"
  CloudinarySettings__ApiKey="878976138233644"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
